name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Buf Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup buf cli
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run buf lint checks
        uses: bufbuild/buf-lint-action@v1

      - name: Run buf format checks
        run: buf format --diff --exit-code

      # TODO: enable at public beta
      #- name: Run buf breaking change detector
      #  uses: bufbuild/buf-breaking-action@v1
      #  with:
      #    against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
